### ISSUE TITLE
(BUG) Segmentation Fault on Apple Silicon when Compiling Shaders

### ISSUE THREAD

**Issue by Tremeschin** [BrokenSource/ShaderFlow#4]
Related DepthFlow issue: https://github.com/BrokenSource/DepthFlow/issues/13

**Comment by jennsun** [comment]
I am running into this issue as well every time I run any of the demos using `shaderflow demoname` -- have you been able to get any of the demos working?

**Comment by Tremeschin** [comment]
closing issue as fixed, better explained on https://github.com/BrokenSource/DepthFlow/issues/13

should work on apple silicon hardware on pypi v0.6.0+ and current git main !
