### ISSUE TITLE
cannot import name 'ShaderProgram' from 'ShaderFlow.Shader'

### ISSUE THREAD

**Issue by alexhorsa** [BrokenSource/ShaderFlow#9]
### 🔘 Request type

User experience

### 🔘 Description

Hi, I am trying to run the demo, I copied the files from Examples folder into Documents\BrokenSource\ShaderFlow\Projects\

This is the error throwed by Demo.py

> cannot import name 'ShaderProgram' from 'ShaderFlow.Shader'

```
BrokenSource\ShaderFlow\Projects\Demo.py:10 in <module>                  │
│                                                                                                  │
│     7 from ShaderFlow.Common.Notes import BrokenPianoNote                                        │
│     8 from ShaderFlow.Modules.Dynamics import ShaderDynamics                                     │
│     9 from ShaderFlow.Scene import ShaderScene                                                   │
│ >  10 from ShaderFlow.Shader import ShaderProgram                                                │
│    11 from ShaderFlow.Texture import ShaderTexture, TextureFilter                                │
│    12 from ShaderFlow.Variable import ShaderVariable, Uniform                                    │
│    13
```

**Comment by Tremeschin** [comment]
I've recently renamed this class on commit https://github.com/BrokenSource/ShaderFlow/commit/b51e3bfc0864f50357d32a71d509769216be6531, you can convert all occurences of `ShaderProgram` in the `Demo.py` file to `ShaderObject` and it should work running from current v0.8 executable or PyPI releases, which uses this old name :)

I could bundle the tech demos into the releases themselves, but it might clutter the CLI for regular usage 😅
